------------------------------------------------------------------
-- ADVANCED WAREHOUSING: INDEXING, MATERIALIZED VIEWS, PARTITIONING
------------------------------------------------------------------

--------------------------------------------------------------------
-- 1. INDEXING
--------------------------------------------------------------------

-- 1a. B-Tree index on date_key
-- =====================================================================
-- Justification: B-Tree range scan optimization. Nearly every query 
-- filters or groups through dim_date. Date ranges are highly selective 
-- (e.g., selecting 1 year out of 10), allowing the query planner to 
-- favor an Index Scan or Bitmap Index Scan over a full table scan.
DROP INDEX IF EXISTS dw_etl.idx_fact_transactions_date_key;
CREATE INDEX idx_fact_transactions_date_key
ON dw_etl.fact_transactions USING btree (date_key);

-- Test B-Tree index performance
EXPLAIN ANALYZE
SELECT COUNT(*) AS num_transactions
FROM dw_etl.fact_transactions f
JOIN dw_etl.dim_date d ON f.date_key = d.date_key
WHERE d.full_date BETWEEN '2013-01-01' AND '2013-12-31';


-- 1b. B-Tree index on customer_key
-- =====================================================================
-- Justification: Point-lookup acceleration. Accelerates highly selective 
-- queries filtering by individual customer (e.g., WHERE customer_key = 1001). 
-- Note: Does NOT optimize full-table customer aggregations/rankings without 
-- filters, where PostgreSQL naturally defaults to a sequential scan + hash aggregate.
DROP INDEX IF EXISTS dw_etl.idx_fact_transactions_customer_key;
CREATE INDEX idx_fact_transactions_customer_key
ON dw_etl.fact_transactions USING btree (customer_key);

-- Test index performance
EXPLAIN ANALYZE
SELECT customer_key, ROUND(SUM(amount), 2) AS total_spent
FROM dw_etl.fact_transactions
WHERE customer_key = 1001
GROUP BY customer_key;


-- 1c. Partial index on fraud_label = TRUE
-- =====================================================================
-- Justification: Specialized partial filtering. Fraud accounts for a tiny 
-- fraction of all records. This compact partial index speeds up queries 
-- filtering strictly for fraudulent activity (e.g., WHERE fraud_label = TRUE). 
-- Note: Queries calculating overall fraud rates (which count both TRUE and 
-- FALSE rows) will perform sequential scans as both populations are required.
DROP INDEX IF EXISTS dw_etl.idx_fact_transactions_fraud_true;
CREATE INDEX idx_fact_transactions_fraud_true
ON dw_etl.fact_transactions (fraud_label)
WHERE fraud_label = TRUE;

-- Test index performance
EXPLAIN ANALYZE
SELECT COUNT(*) AS num_frauds
FROM dw_etl.fact_transactions
WHERE fraud_label = TRUE;


-- 1d. B-Tree index on location_key
-- =====================================================================
-- Justification: Foreign Key join & dimension filtering. City/state 
-- filtering occurs on dim_location first (e.g., WHERE merchant_state = 'CA'). 
-- This index enables nested loop / hash joins from selective dim_location 
-- keys directly into fact_transactions without scanning unrelated facts.
DROP INDEX IF EXISTS dw_etl.idx_fact_transactions_location_key;
CREATE INDEX idx_fact_transactions_location_key
ON dw_etl.fact_transactions USING btree (location_key);

-- Test index performance
EXPLAIN ANALYZE
SELECT loc.merchant_state, COUNT(*) AS num_transactions
FROM dw_etl.fact_transactions f
JOIN dw_etl.dim_location loc ON f.location_key = loc.location_key
WHERE loc.merchant_state = 'CA'
GROUP BY loc.merchant_state;


-- 1e. B-Tree index on card_key (NEW - NL-to-SQL Agent Workload)
-- =====================================================================
-- Justification: Ad-hoc query optimization for GenAI/LLM layer. 
-- The fixed BI dashboard does not perform selective lookups on cards, 
-- but the NL-to-SQL agent frequently executes point lookups or card-level 
-- histories (e.g., "Show recent transactions for card ID X").
DROP INDEX IF EXISTS dw_etl.idx_fact_transactions_card_key;
CREATE INDEX idx_fact_transactions_card_key
ON dw_etl.fact_transactions USING btree (card_key);

-- Test index performance
EXPLAIN ANALYZE
SELECT transaction_id, amount, date_key
FROM dw_etl.fact_transactions
WHERE card_key = 500
ORDER BY date_key DESC;


-- 1f. B-Tree index on mcc_key (NEW - NL-to-SQL Agent Workload)
-- =====================================================================
-- Justification: Ad-hoc query optimization for GenAI/LLM layer. 
-- Supports dynamic merchant category code filtering generated by the LLM 
-- agent (e.g., "Find all grocery store transactions [MCC 5411] in 2018").
DROP INDEX IF EXISTS dw_etl.idx_fact_transactions_mcc_key;
CREATE INDEX idx_fact_transactions_mcc_key
ON dw_etl.fact_transactions USING btree (mcc_key);

-- Test index performance
EXPLAIN ANALYZE
SELECT COUNT(*), SUM(amount)
FROM dw_etl.fact_transactions
WHERE mcc_key = 12
GROUP BY mcc_key;


--------------------------------------------------------------------
-- 2. MATERIALIZED VIEW
--------------------------------------------------------------------
-- Justification: DSS aggregation caching. Precomputes a heavy 3-way join 
-- and group-by (Year, Month, State) not captured in static MOLAP tables.
-- Eliminates fact-table scans for interactive monthly geospatial fraud reporting.

DROP MATERIALIZED VIEW IF EXISTS dw_etl.mv_monthly_fraud_summary;

CREATE MATERIALIZED VIEW dw_etl.mv_monthly_fraud_summary AS
SELECT
    d.year,
    d.month,
    loc.merchant_state,
    COUNT(*) AS num_transactions,
    SUM(CASE WHEN f.fraud_label THEN 1 ELSE 0 END) AS num_frauds,
    SUM(f.amount) AS total_amount
FROM dw_etl.fact_transactions f
JOIN dw_etl.dim_date d ON f.date_key = d.date_key
JOIN dw_etl.dim_location loc ON f.location_key = loc.location_key
GROUP BY d.year, d.month, loc.merchant_state
ORDER BY d.year, d.month, loc.merchant_state;

-- Unique index required for non-blocking concurrent refreshes
CREATE UNIQUE INDEX idx_mv_monthly_fraud_summary_uniq
ON dw_etl.mv_monthly_fraud_summary (year, month, merchant_state);

-- Test query on materialized view
EXPLAIN ANALYZE
SELECT *
FROM dw_etl.mv_monthly_fraud_summary
WHERE merchant_state = 'CA'
ORDER BY year, month;


--------------------------------------------------------------------
-- 3. PARTITIONING
--------------------------------------------------------------------
-- Rationale: Range partitioning on full_date (2010–2019 + DEFAULT) to 
-- enable Partition Pruning during time-bounded queries.
--
-- NOTE: dw_etl.partitioned_fact_transactions is a standalone benchmark/demo 
-- copy used to evaluate pruning performance against dw_etl.fact_transactions. 
-- Production writes land on dw_etl.fact_transactions via etl.sql.

-- 1. Create parent table WITHOUT the PK/UNIQUE constraints for now
DROP TABLE IF EXISTS dw_etl.partitioned_fact_transactions CASCADE;

CREATE TABLE dw_etl.partitioned_fact_transactions (
    fact_id         BIGSERIAL,
    transaction_id  BIGINT NOT NULL,
    full_date       DATE NOT NULL,
    customer_key    BIGINT REFERENCES dw_etl.dim_customer(customer_key),
    card_key        BIGINT REFERENCES dw_etl.dim_card(card_key),
    merchant_key    BIGINT REFERENCES dw_etl.dim_merchant(merchant_key),
    location_key    BIGINT REFERENCES dw_etl.dim_location(location_key),
    mcc_key         BIGINT REFERENCES dw_etl.dim_mcc(mcc_key),
    amount          NUMERIC(18,2),
    use_chip        BOOLEAN,
    fraud_label     BOOLEAN,
    anomaly_flag    BOOLEAN DEFAULT FALSE,
    error_key       BIGINT REFERENCES dw_etl.dim_error(error_key)
) PARTITION BY RANGE (full_date);

-------------------------------------------------
-- 2. Create all 10 yearly partitions + DEFAULT (no indexes yet)
-------------------------------------------------
CREATE TABLE dw_etl.partitioned_fact_transactions_2010
    PARTITION OF dw_etl.partitioned_fact_transactions
    FOR VALUES FROM ('2010-01-01') TO ('2011-01-01');

CREATE TABLE dw_etl.partitioned_fact_transactions_2011
    PARTITION OF dw_etl.partitioned_fact_transactions
    FOR VALUES FROM ('2011-01-01') TO ('2012-01-01');

CREATE TABLE dw_etl.partitioned_fact_transactions_2012
    PARTITION OF dw_etl.partitioned_fact_transactions
    FOR VALUES FROM ('2012-01-01') TO ('2013-01-01');

CREATE TABLE dw_etl.partitioned_fact_transactions_2013
    PARTITION OF dw_etl.partitioned_fact_transactions
    FOR VALUES FROM ('2013-01-01') TO ('2014-01-01');

CREATE TABLE dw_etl.partitioned_fact_transactions_2014
    PARTITION OF dw_etl.partitioned_fact_transactions
    FOR VALUES FROM ('2014-01-01') TO ('2015-01-01');

CREATE TABLE dw_etl.partitioned_fact_transactions_2015
    PARTITION OF dw_etl.partitioned_fact_transactions
    FOR VALUES FROM ('2015-01-01') TO ('2016-01-01');

CREATE TABLE dw_etl.partitioned_fact_transactions_2016
    PARTITION OF dw_etl.partitioned_fact_transactions
    FOR VALUES FROM ('2016-01-01') TO ('2017-01-01');

CREATE TABLE dw_etl.partitioned_fact_transactions_2017
    PARTITION OF dw_etl.partitioned_fact_transactions
    FOR VALUES FROM ('2017-01-01') TO ('2018-01-01');

CREATE TABLE dw_etl.partitioned_fact_transactions_2018
    PARTITION OF dw_etl.partitioned_fact_transactions
    FOR VALUES FROM ('2018-01-01') TO ('2019-01-01');

CREATE TABLE dw_etl.partitioned_fact_transactions_2019
    PARTITION OF dw_etl.partitioned_fact_transactions
    FOR VALUES FROM ('2019-01-01') TO ('2020-01-01');

-- Catch-all partition for out-of-range bounds or 1900-01-01 fallbacks
CREATE TABLE dw_etl.partitioned_fact_transactions_default
    PARTITION OF dw_etl.partitioned_fact_transactions
    DEFAULT;

-------------------------------------------------
-- 3. Populate Partitioned Benchmark Copy (Raw Writes)
-------------------------------------------------
INSERT INTO dw_etl.partitioned_fact_transactions (
    transaction_id, full_date, customer_key, card_key,
    merchant_key, location_key, mcc_key, amount, use_chip, fraud_label,
    anomaly_flag, error_key
)
SELECT
    f.transaction_id,
    d.full_date,
    f.customer_key, f.card_key, f.merchant_key, f.location_key, f.mcc_key,
    f.amount, f.use_chip, f.fraud_label,
    f.anomaly_flag, f.error_key
FROM dw_etl.fact_transactions f
JOIN dw_etl.dim_date d ON d.date_key = f.date_key;

-------------------------------------------------
-- 4. Add PK, UNIQUE constraint, and all 5 secondary indexes
-------------------------------------------------
-- Increase maintenance_work_mem to accelerate bulk index builds
SET maintenance_work_mem = '1GB'; 

ALTER TABLE dw_etl.partitioned_fact_transactions
  ADD PRIMARY KEY (fact_id, full_date);
  
ALTER TABLE dw_etl.partitioned_fact_transactions
  ADD CONSTRAINT uq_part_fact_txn_date UNIQUE (transaction_id, full_date);

CREATE INDEX idx_part_fact_customer_key
    ON dw_etl.partitioned_fact_transactions (customer_key);

CREATE INDEX idx_part_fact_location_key
    ON dw_etl.partitioned_fact_transactions (location_key);

CREATE INDEX idx_part_fact_card_key
    ON dw_etl.partitioned_fact_transactions (card_key);

CREATE INDEX idx_part_fact_mcc_key
    ON dw_etl.partitioned_fact_transactions (mcc_key);

CREATE INDEX idx_part_fact_fraud_true
    ON dw_etl.partitioned_fact_transactions (fraud_label)
    WHERE fraud_label = TRUE;

-------------------------------------------------
-- 5. Analyze and Run Verification/Benchmark Queries
-------------------------------------------------
-- Ensure the query planner has up-to-date statistics before benchmarking
ANALYZE dw_etl.partitioned_fact_transactions;

-- Check Partition Pruning (Planner scans only the 2013 partition table)
EXPLAIN ANALYZE
SELECT COUNT(*)
FROM dw_etl.partitioned_fact_transactions
WHERE full_date BETWEEN '2013-01-01' AND '2013-12-31';

-- Verify counts match between primary fact table and partitioned table
SELECT
    (SELECT COUNT(*) FROM dw_etl.fact_transactions)                       AS source_fact_count,
    (SELECT COUNT(*) FROM dw_etl.partitioned_fact_transactions)           AS partitioned_fact_count,
    (SELECT COUNT(*) FROM dw_etl.partitioned_fact_transactions_default) AS rows_in_default_partition;

	